server:
  port: 8086

spring:
  data:
    mongodb:
      uri: mongodb+srv://leonel:leonel@cluster0.we5wo.mongodb.net/bank
      
eureka:
  client:
    service-url:
        defaultZone: http://localhost:8096/eureka
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

restClient:
   customerUrl: http://gateway-server-service/api/customer
   transactionUrl: http://gateway-server-service/api/transaction
   creditUrl: http://gateway-server-service/api/credit
   debitCardUrl: http://gateway-server-service/api/debitcard

